// P0-2 (audit COMMON-05): projects are named after their source instead of
// asking, and the first export of an auto-named project offers a rename once.
const { loadSource } = require('./_helpers/loadSource');

function loadHelpers() {
  const src = loadSource('helpers.js');
  const start = src.indexOf('var UNTITLED_DESIGN_NAME');
  const end = src.indexOf('// IndexedDB utility functions', start);
  // eslint-disable-next-line no-new-func
  return new Function(src.slice(start, end).replace(/if\(typeof window[^\n]*\n/, '') +
    '\nreturn { projectNameFromFile: projectNameFromFile, UNTITLED_DESIGN_NAME: UNTITLED_DESIGN_NAME };')();
}

describe('projectNameFromFile', () => {
  const { projectNameFromFile, UNTITLED_DESIGN_NAME } = loadHelpers();

  test('drops the extension', () => {
    expect(projectNameFromFile('IMG_2041.JPG')).toBe('IMG_2041');
    expect(projectNameFromFile('logo.png')).toBe('logo');
  });

  test('keeps dots inside the name and strips folders', () => {
    expect(projectNameFromFile('rose.garden.v2.jpeg')).toBe('rose.garden.v2');
    expect(projectNameFromFile('C:\\pics\\cat.webp')).toBe('cat');
    expect(projectNameFromFile('/tmp/dog.gif')).toBe('dog');
  });

  test('a dot-file keeps its name', () => {
    expect(projectNameFromFile('.hidden')).toBe('.hidden');
  });

  test('empty names fall back to "Untitled design"', () => {
    expect(UNTITLED_DESIGN_NAME).toBe('Untitled design');
    expect(projectNameFromFile('')).toBe('Untitled design');
    expect(projectNameFromFile(null)).toBe('Untitled design');
    expect(projectNameFromFile('   .png')).toBe('Untitled design');
  });

  test('collapses whitespace and caps the length at 60', () => {
    expect(projectNameFromFile('  my   photo .jpg')).toBe('my photo');
    expect(projectNameFromFile('a'.repeat(80) + '.png')).toHaveLength(60);
  });
});

describe('nameAutoGenerated wiring', () => {
  const io = loadSource('creator/useProjectIO.js');
  const st = loadSource('creator/useCreatorState.js');
  const main = loadSource('creator-main.js');

  test('saved with the project in every Creator save path and restored on load', () => {
    expect((io.match(/nameAutoGenerated: !!state\.nameAutoGenerated,/g) || []).length).toBe(3);
    expect(io).toMatch(/state\.setNameAutoGenerated\(!!project\.nameAutoGenerated\)/);
  });

  test('conversion names the project after the image, scratch is "Untitled design"', () => {
    expect(io).toMatch(/window\.projectNameFromFile\(f\.name\)/);
    expect(st).toMatch(/setAutoProjectName\(window\.UNTITLED_DESIGN_NAME/);
  });

  test('the first save no longer opens the name prompt', () => {
    expect(io).not.toMatch(/setNamePromptOpen\(true\)[\s\S]{0,40}\}\s*\}, \{ debounceMs/);
    expect(io).not.toMatch(/setNameModalReason\("firstSave"\)/);
  });

  test('renaming clears the flag', () => {
    expect(st).toMatch(/var renameProject = useCallback\(function\(name\) \{\s*setProjectName\(name\);\s*setNameAutoGenerated\(false\);/);
    expect(main).toMatch(/onNameChange=\{state\.pat&&state\.pal\?n=>state\.renameProject\(n\):undefined\}/);
  });

  test('the export-time prompt uses the agreed copy with Skip', () => {
    expect(main).toMatch(/Give this pattern a name\? It will appear on the PDF and in your library\./);
    expect(main).toMatch(/cancelLabel:'Skip'/);
  });

  test('imports named after the file are marked auto-named; a review rename clears it', () => {
    const wire = loadSource('import-engine/wireApp.js');
    expect(wire).toMatch(/result\.project\.nameAutoGenerated = true;/);
    const review = loadSource('import-engine/ui/ImportReviewModal.js');
    expect(review).toMatch(/next\.nameAutoGenerated = false;/);
  });
});
